# Server Configuration
server.port=8081
spring.application.name=user-service

# Supabase PostgreSQL Connection (Pooler)
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.aerbwuestllgfhihkntt
spring.datasource.password=Divanshu@710
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=MySecretKeyForCodingAppMustBeAtLeast32BytesLong123456789
jwt.expiration-ms=86400000