# Server Configuration
server.port=8084
spring.application.name=test-service

# Database Connection (Injected from Environment Variables)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&prepareThreshold=0
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Microservice Communication Configuration
problem-service.url=http://localhost:8082
user-service.url=http://localhost:8081

## Kafka Producer Configuration
#spring.kafka.producer.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379